<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-S0R30VE" ignored="1" name="Default test" tests="4" failures="1" timestamp="28 fev 2017 22:26:16 GMT" time="42.772" errors="0">
  <testcase name="cpfInvalido" time="17.126" classname="br.com.gcs.test.CL_MeusDadosTest"/>
  <testcase name="nomeIncompleto" time="4.242" classname="br.com.gcs.test.CL_MeusDadosTest"/>
  <testcase name="dataInvalida" time="3.259" classname="br.com.gcs.test.CL_MeusDadosTest">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;Data Incorreta[X]&amp;gt; but was:&amp;lt;Data Incorreta[]&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<Data Incorreta[X]> but was:<Data Incorreta[]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at br.com.gcs.test.CL_MeusDadosTest.dataInvalida(CL_MeusDadosTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- dataInvalida -->
  <testcase name="validarRenda" time="5.341" classname="br.com.gcs.test.CL_MeusDadosTest"/>
  <testcase name="avancar" time="0.0" classname="br.com.gcs.test.CL_MeusDadosTest">
    <ignored/>
  </testcase> <!-- avancar -->
</testsuite> <!-- Default test -->
